### ISSUE TITLE
Broken after Update

### ISSUE THREAD

**Issue by MetalHeadSeven** [Backupiseasy/ThreatPlates#543]
Getting 5 Errors.

1x TidyPlates_ThreatPlates/Init.lua:148: attempt to call field 'GetSpellInfo' (a nil value)
[string "@TidyPlates_ThreatPlates/Init.lua"]:148: in function <TidyPlates_ThreatPlates/Init.lua:146>
[string "@TidyPlates_ThreatPlates/Constants.lua"]:512: in function `InitializeTotemInformation'
[string "@TidyPlates_ThreatPlates/Constants.lua"]:538: in function `GetDefaultTotemSettings'
[string "@TidyPlates_ThreatPlates/Constants.lua"]:1713: in main chunk

Locals:
(*temporary) = nil
(*temporary) = 2484
(*temporary) = "attempt to call field 'GetSpellInfo' (a nil value)"

------------------------------------------------------------------------------------------------------------------------------------------------------

1x TidyPlates_ThreatPlates/Init.lua:223: attempt to index field 'customtext' (a nil value)
[string "@TidyPlates_ThreatPlates/Init.lua"]:223: in function `LoadOnDemandLibraries'
[string "@TidyPlates_ThreatPlates/Core.lua"]:381: in function <TidyPlates_ThreatPlates/Core.lua:364>
[string "=[C]"]: ?
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
db = <table> {
 threatWidget = <table> {
 }
 threat = <table> {
 }
 settings = <table> {
 }
 Automation = <table> {
 }
 HeadlineView = <table> {
 }
 Visibility = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'customtext' (a nil value)"
Addon = <table> {
 IS_WRATH_CLASSIC = false
 Theme = <table> {
 }
 TotemCreatureType = "Totem"
 AurasFilterMode = <table> {
 }
 ANCHOR_POINT_SETPOINT = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 UIScale = 1
 Font = <table> {
 }
 WOW_USES_CLASSIC_NAMEPLATES = false
 IGNORED_STYLES = <table> {
 }
 PlatesByUnit = <table> {
 }
 Animations = <table> {
 }
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 IS_TBC_CLASSIC = false
 MODE_FOR_STYLE = <table> {
 }
 TotemInformation = <table> {
 }
 ON_UPDATE_PER_FRAME = 0.016667
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 Debug = <table> {
 }
 PlatesByGUID = <table> {
 }
 EventHandler = <table> {
 }
 LibUTF8 = <table> {
 }
 Logging = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 ANCHOR_POINT = <table> {
 }
 PlayerName = "Cayna"
 TOTEMS = <table> {
 }
 SCRIPT_FUNCTIONS = <table> {
 }
 ON_UPDATE_INTERVAL = 0.250000
 IS_CATA_CLASSIC = false
 IS_CLASSIC = false
 LibAceConfigRegistry = <table> {
 }
 LibAceConfigDialog = <table> {
 }
 db = <table> {
 }
 WIDGET_EVENTS = <table> {
 }
 IS_CLASSIC_SOD = false
 Widgets = <table> {
 }
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 IS_TWW = false
 Cache = <table> {
 }
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 IS_MAINLINE = true
 LibCustomGlow = <table> {
 }
 DEFAULT_FONT = "Cabin"
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 BackdropTemplate = "BackdropTemplate"
 DEBUG = true
 LibSharedMedia = <table> {
 }
 PlatesCreated = <table> {
 }
 Data = <table> {
 }
 LEGACY_CUSTOM_NAMEPLATES = <table> {
 }
 DEFAULT_SMALL_FONT = "Arial Narrow"
 PlayerClass = "PALADIN"
 GLOW_TYPES = <table> {
 }
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 PlatesVisible = <table> {
 }
}
LibStub = <table> {
 minors = <table> {
 }
 minor = 2
 libs = <table> {
 }
}
L = <table> {
 On Target = "On Target"
 About = "About"
 This will toggle the auras widget to show the cooldown spiral on auras. = "This will toggle the auras widget to show the cooldown spiral on auras."
 Alpha multiplier of nameplates for occluded units. = "Alpha multiplier of nameplates for occluded units."
 This will allow you to disable threat art on target marked units. = "This will allow you to disable threat art on target marked units."
 Quest = "Quest"
 Ebon Gargoyle = "Ebon Gargoyle"
 Alpha = "Alpha"
 Aura:  = "Aura: "
 Low Priority = "Low Priority"
 Note = "Note"
 Situational Scale = "Situational Scale"
 This lets you select the layout style of the auras area. = "This lets you select the layout style of the auras area."
 Typeface = "Typeface"
 Change the transparency of nameplates for occluded units (e.g., units behind walls). = "Change the transparency of nameplates for occluded units (e.g., units behind walls)."
 Size = "Size"
 The inset from the top (in screen percent) that the non-self nameplates are clamped to. = "The inset from the top (in screen percent) that the non-self nameplates are clamped to."
 Text Height = "Text Height"
 Layout = "Layout"
 Use target scale and transparency settings also for soft interact target. = "Use target scale and transparency settings also for soft interact target."
 Font = "Font"
 WoW Round = "WoW Round"
 General Settings = "General Settings"
 |cff00ff00High Threat|r = "|cff00ff00High Threat|r"
 Art Options = "Art Options"
 Top Inset = "Top Inset"
 Thick Outline, Monochrome = "Thick Outline, Monochrome"
 Nameplate Style = "Nameplate Style"
 Healthbar, Castbar = "Healthbar, Castbar"
 This option allows you to control whether threat affects the transparency of nameplates. = "This option allows you to control whether threat affects the transparency of nameplates."
 One = "One"
 These options allow you to control whether target marker icon

---------------------------------------------------------------------------------------------------------------------------------------------------

2x ...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1792: attempt to call method 'UIScaleChanged' (a nil value)
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1792: in function `?'
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1302: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1301>

Locals:
self = "UI_SCALE_CHANGED"
(*temporary) = nil
(*temporary) = <table> {
 IS_WRATH_CLASSIC = false
 Theme = <table> {
 }
 TotemCreatureType = "Totem"
 AurasFilterMode = <table> {
 }
 ANCHOR_POINT_SETPOINT = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 UIScale = 1
 Font = <table> {
 }
 WOW_USES_CLASSIC_NAMEPLATES = false
 IGNORED_STYLES = <table> {
 }
 PlatesByUnit = <table> {
 }
 Animations = <table> {
 }
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 IS_TBC_CLASSIC = false
 MODE_FOR_STYLE = <table> {
 }
 TotemInformation = <table> {
 }
 ON_UPDATE_PER_FRAME = 0.016667
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 Debug = <table> {
 }
 PlatesByGUID = <table> {
 }
 EventHandler = <table> {
 }
 LibUTF8 = <table> {
 }
 Logging = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 ANCHOR_POINT = <table> {
 }
 PlayerName = "Cayna"
 TOTEMS = <table> {
 }
 SCRIPT_FUNCTIONS = <table> {
 }
 ON_UPDATE_INTERVAL = 0.250000
 IS_CATA_CLASSIC = false
 IS_CLASSIC = false
 LibAceConfigRegistry = <table> {
 }
 LibAceConfigDialog = <table> {
 }
 db = <table> {
 }
 WIDGET_EVENTS = <table> {
 }
 IS_CLASSIC_SOD = false
 Widgets = <table> {
 }
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 IS_TWW = false
 Cache = <table> {
 }
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 IS_MAINLINE = true
 LibCustomGlow = <table> {
 }
 DEFAULT_FONT = "Cabin"
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 BackdropTemplate = "BackdropTemplate"
 DEBUG = true
 LibSharedMedia = <table> {
 }
 PlatesCreated = <table> {
 }
 Data = <table> {
 }
 LEGACY_CUSTOM_NAMEPLATES = <table> {
 }
 DEFAULT_SMALL_FONT = "Arial Narrow"
 PlayerClass = "PALADIN"
 GLOW_TYPES = <table> {
 }
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 PlatesVisible = <table> {
 }
}
(*temporary) = "attempt to call method 'UIScaleChanged' (a nil value)"
Addon = <table> {
 IS_WRATH_CLASSIC = false
 Theme = <table> {
 }
 TotemCreatureType = "Totem"
 AurasFilterMode = <table> {
 }
 ANCHOR_POINT_SETPOINT = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 UIScale = 1
 Font = <table> {
 }
 WOW_USES_CLASSIC_NAMEPLATES = false
 IGNORED_STYLES = <table> {
 }
 PlatesByUnit = <table> {
 }
 Animations = <table> {
 }
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 IS_TBC_CLASSIC = false
 MODE_FOR_STYLE = <table> {
 }
 TotemInformation = <table> {
 }
 ON_UPDATE_PER_FRAME = 0.016667
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 Debug = <table> {
 }
 PlatesByGUID = <table> {
 }
 EventHandler = <table> {
 }
 LibUTF8 = <table> {
 }
 Logging = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 ANCHOR_POINT = <table> {
 }
 PlayerName = "Cayna"
 TOTEMS = <table> {
 }
 SCRIPT_FUNCTIONS = <table> {
 }
 ON_UPDATE_INTERVAL = 0.250000
 IS_CATA_CLASSIC = false
 IS_CLASSIC = false
 LibAceConfigRegistry = <table> {
 }
 LibAceConfigDialog = <table> {
 }
 db = <table> {
 }
 WIDGET_EVENTS = <table> {
 }
 IS_CLASSIC_SOD = false
 Widgets = <table> {
 }
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 IS_TWW = false
 Cache = <table> {
 }
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 IS_MAINLINE = true
 LibCustomGlow = <table> {
 }
 DEFAULT_FONT = "Cabin"
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 BackdropTemplate = "BackdropTemplate"
 DEBUG = true
 LibSharedMedia = <table> {
 }
 PlatesCreated = <table> {
 }
 Data = <table> {
 }
 LEGACY_CUSTOM_NAMEPLATES = <table> {
 }
 DEFAULT_SMALL_FONT = "Arial Narrow"
 PlayerClass = "PALADIN"
 GLOW_TYPES = <table> {
 }
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 PlatesVisible = <table> {
 }
}

---------------------------------------------------------------------------------------------------------------------------------------------------

1x TidyPlates_ThreatPlates/Core.lua:410: attempt to index field 'PersonalNameplate' (a nil value)
[string "@TidyPlates_ThreatPlates/Core.lua"]:410: in function <TidyPlates_ThreatPlates/Core.lua:405>
[string "=[C]"]: ?
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function <...rfaceBlizzard_UIParent/Mainline/UIParent.lua:421>
[string "=[C]"]: in function `UIParentLoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:103: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:96: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:91: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:83: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:79>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
self = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "TidyPlatesThreat"
 orderedModules = <table> {
 }
 baseName = "TidyPlates_ThreatPlates"
 enabledState = true
 defaultModuleState = true
}
(*temporary) = <table> {
}
(*temporary) = "nameplateResourceOnTarget"
(*temporary) = nil
(*temporary) = "attempt to index field 'PersonalNameplate' (a nil value)"
Addon = <table> {
 IS_WRATH_CLASSIC = false
 Theme = <table> {
 }
 TotemCreatureType = "Totem"
 AurasFilterMode = <table> {
 }
 ANCHOR_POINT_SETPOINT = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 UIScale = 1
 Font = <table> {
 }
 WOW_USES_CLASSIC_NAMEPLATES = false
 IGNORED_STYLES = <table> {
 }
 PlatesByUnit = <table> {
 }
 Animations = <table> {
 }
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 IS_TBC_CLASSIC = false
 MODE_FOR_STYLE = <table> {
 }
 TotemInformation = <table> {
 }
 ON_UPDATE_PER_FRAME = 0.016667
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 Debug = <table> {
 }
 PlatesByGUID = <table> {
 }
 EventHandler = <table> {
 }
 LibUTF8 = <table> {
 }
 Logging = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 ANCHOR_POINT = <table> {
 }
 PlayerName = "Cayna"
 TOTEMS = <table> {
 }
 SCRIPT_FUNCTIONS = <table> {
 }
 ON_UPDATE_INTERVAL = 0.250000
 IS_CATA_CLASSIC = false
 IS_CLASSIC = false
 LibAceConfigRegistry = <table> {
 }
 LibAceConfigDialog = <table> {
 }
 db = <table> {
 }
 WIDGET_EVENTS = <table> {
 }
 IS_CLASSIC_SOD = false
 Widgets = <table> {
 }
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 IS_TWW = false
 Cache = <table> {
 }
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 IS_MAINLINE = true
 LibCustomGlow = <table> {
 }
 DEFAULT_FONT = "Cabin"
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 BackdropTemplate = "BackdropTemplate"
 DEBUG = true
 LibSharedMedia = <table> {
 }
 PlatesCreated = <table> {
 }
 Data = <table> {
 }
 LEGACY_CUSTOM_NAMEPLATES = <table> {
 }
 DEFAULT_SMALL_FONT = "Arial Narrow"
 PlayerClass = "PALADIN"
 GLOW_TYPES = <table> {
 }
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 PlatesVisible = <table> {
 }
}
CVars = <table> {
}

---------------------------------------------------------------------------------------------------------------------------------------------------

2x ...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1869: attempt to call field 'UnitBuff' (a nil value)
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1869: in function `UNIT_AURA'
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1965: in main chunk

Locals:
event = nil
unitid = nil
(for index) = 1
(for limit) = 40
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = "player"
(*temporary) = 1
(*temporary) = "PLAYER"
(*temporary) = "attempt to call field 'UnitBuff' (a nil value)"
_G = <table> {
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 HUD_EDIT_MODE_SETTING_ACTION_BAR_HIDE_BAR_ART = "Hide Bar Art"
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 784
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 422
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Attached to the left side of Right Action Bar 1 by default"
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 376
 MerchantItem3AltCurrencyFrameItem1Text = MerchantItem3AltCurrencyFrameItem1Text {
 }
 PROFESSIONS_COLUMN_REAGENTS_NONE = "None"
 OPTION_SHOW_ACTION_BAR5_TOOLTIP = "Attached to the left side of Action Bar 4 by default"
 BINDING_NAME_NAMEPLATES = "Show Enemy Nameplates"
 CHAT_HEADER_SUFFIX = ": "
 COVENANT_MISSIONS_HEALTH = "Health"
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 MultiBar6Button4Flash = MultiBar6Button4Flash {
 }
 CALENDAR_RAID_RESET_DESCRIPTION = "%1$s resets at %2$s."
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 ClassNameplateBarPaladinFrameRune5 = ClassNameplateBarPaladinFrameRune5 {
 }
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 CinematicFrameRaidBossEmoteFrame = CinematicFrameRaidBossEmoteFrame {
 }
 LE_GAME_ERR_ONLY_ONE_QUIVER = 36
 INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
 SLASH_LibQTip1 = "/qtip"
 BtWQuestsSearchResultFullMixin = <table> {
 }
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 MacroFrame = MacroFrame {
 }
 POWERBAR_PREDICTION_COLOR_MAELSTROM_CODE = "|cff003366"
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 DMG_LCD = "DMG"
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 SLASH_STOPATTACK1 = "/stopattack"
 MAP_LEGEND_RARE_TOOLTIP = "A special creature that provides various rewards"
 MultiCastActionButton4HotKey = MultiCastActionButton4HotKey {
 }
 MINIMAP_TRACKING_TRAINER_CLASS = "Class Trainer"
 SLASH_DISMOUNT2 = "/dismount"
 DUNGEON_FLOOR_DRAGONBLIGHTCHROMIESCENARIO2 = "Andorhal"
 DetailsFrameworkBarNumber840712 = DetailsFrameworkBarNumber840712 {
 }
 NarciSoulbindsActivateButtonMixin = <table> {
 }
 EMOTE69_CMD1 = "/nosepick"
 WowTokenRedemptionFrameBg = WowTokenRedemptionFrameBg {
 }
 SHIELD_BLOCK_TEMPLATE = "%s Block"
 AutoFollowStatus = AutoFollowStatus {
 }
 ARENA_CASUAL = "Skirmish"
 STABLE_PET_ABILITIES_LIST_HEADER = "Special Abilities"
 SendStationeryBackgroundRight = SendStationeryBackgroundRight {
 }
 MultiBarLeftButton11Name = MultiBarLeftButton11Name {
 }
 TUTORIAL61_SPELLID_DRUID = "768"
 CONQUEST_BAR = "Conquest %d / %d"
 MultiBarLeftButton9Border = MultiBarLeftButton9Border {
 }
 POSTMASTER_PIPE_KALIMDOR = "Kalimdor"
 UIWidgetCenterDisplayFrameText = UIWidgetCenterDisplayFrameText {
 }
 OPTION_TOOLTIP_SHOW_ACCOUNT_ACHIEVEMENTS = "Turning this option on will only display your character achievements when people inspect you or use the Blizzard website or mobile app."
 SPIRIT_HEALER_RELEASE_RED = "|cffff2020Spirit Healer|r"
 OPTION_TOOLTIP_FIX_LAG = "Enabling this reduces user interface lag, but may drastically reduce frame rates."
 ARTIFACT_XP_FULL = "%s is at max leve

**Comment by karpana** [comment]
Adding my errors here as well in the hopes they also provide assistance with the launch of 11.0.2 today.


```lua
3x TidyPlates_ThreatPlates/Init.lua:148: attempt to call field 'GetSpellInfo' (a nil value)
[string "@TidyPlates_ThreatPlates/Init.lua"]:148: in function <TidyPlates_ThreatPlates/Init.lua:146>
[string "@TidyPlates_ThreatPlates/Constants.lua"]:512: in function `InitializeTotemInformation'
[string "@TidyPlates_ThreatPlates/Constants.lua"]:538: in function `GetDefaultTotemSettings'
[string "@TidyPlates_ThreatPlates/Constants.lua"]:1713: in main chunk

Locals:
(*temporary) = nil
(*temporary) = 2484
(*temporary) = "attempt to call field 'GetSpellInfo' (a nil value)"
```



```lua
2x ...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1478: attempt to index local 'db' (a nil value)
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1478: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1457>
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1494: in function `?'
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1302: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1301>

Locals:
target_unitid = "target"
plate = NamePlate4 {
 driverFrame = NamePlateDriverFrame {
 }
 template = "NamePlateUnitFrameTemplate"
 namePlateUnitToken = "nameplate2"
 UnitFrame = Button {
 }
 UpdateMe = false
 TPFrame = ThreatPlatesFrameNamePlate4 {
 }
 TimeSinceLastUpdate = 0
}
db = nil
(*temporary) = ThreatPlatesFrameNamePlate4 {
 WidgetContainer = Frame {
 }
 stylename = ""
 Parent = NamePlate4 {
 }
 unitcache = <table> {
 }
 widgets = <table> {
 }
 style = <table> {
 }
 IsOccluded = false
 Active = true
 visual = <table> {
 }
 unit = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'db' (a nil value)"
LastTargetPlate = <table> {
}
SettingsShowOnlyForTarget = nil
Addon = <table> {
 IS_WRATH_CLASSIC = false
 Theme = <table> {
 }
 TotemCreatureType = "Totem"
 AurasFilterMode = <table> {
 }
 ANCHOR_POINT_SETPOINT = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 UIScale = 1
 Font = <table> {
 }
 WOW_USES_CLASSIC_NAMEPLATES = false
 IGNORED_STYLES = <table> {
 }
 PlatesByUnit = <table> {
 }
 Animations = <table> {
 }
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 IS_TBC_CLASSIC = false
 MODE_FOR_STYLE = <table> {
 }
 TotemInformation = <table> {
 }
 ON_UPDATE_PER_FRAME = 0.020333
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 Debug = <table> {
 }
 PlatesByGUID = <table> {
 }
 EventHandler = <table> {
 }
 LibUTF8 = <table> {
 }
 Logging = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 ANCHOR_POINT = <table> {
 }
 PlayerName = "Karpana"
 TOTEMS = <table> {
 }
 SCRIPT_FUNCTIONS = <table> {
 }
 ON_UPDATE_INTERVAL = 0.250000
 IS_CATA_CLASSIC = false
 IS_CLASSIC = false
 LibAceConfigRegistry = <table> {
 }
 LibAceConfigDialog = <table> {
 }
 db = <table> {
 }
 WIDGET_EVENTS = <table> {
 }
 IS_CLASSIC_SOD = false
 Widgets = <table> {
 }
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 IS_TWW = false
 Cache = <table> {
 }
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 IS_MAINLINE = true
 LibCustomGlow = <table> {
 }
 DEFAULT_FONT = "Cabin"
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 BackdropTemplate = "BackdropTemplate"
 DEBUG = true
 LibSharedMedia = <table> {
 }
 PlatesCreated = <table> {
 }
 Data = <table> {
 }
 LEGACY_CUSTOM_NAMEPLATES = <table> {
 }
 DEFAULT_SMALL_FONT = "Arial Narrow"
 PlayerClass = "PALADIN"
 GLOW_TYPES = <table> {
 }
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 PlatesVisible = <table> {
 }
}
CoreEvents = <table> {
}
```





```lua
24x ...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:330: attempt to index field 'BlizzardSettings' (a nil value)
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:330: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:323>
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:670: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:645>
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1381: in function `?'
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1302: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1301>

Locals:
plate = NamePlate1 {
 driverFrame = NamePlateDriverFrame {
 }
 TPFrame = ThreatPlatesFrameNamePlate1 {
 }
 TimeSinceLastUpdate = 0
 namePlateUnitToken = "nameplate1"
 UnitFrame = Button {
 }
 UpdateMe = false
 template = "NamePlateUnitFrameTemplate"
}
tp_frame = ThreatPlatesFrameNamePlate1 {
 WidgetContainer = Frame {
 }
 stylename = ""
 Parent = NamePlate1 {
 }
 unitcache = <table> {
 }
 widgets = <table> {
 }
 style = <table> {
 }
 IsOccluded = false
 Active = true
 visual = <table> {
 }
 unit = <table> {
 }
}
widget_container = Frame {
 horizontalRelativePoint = "RIGHT"
 horizontalRowContainerPool = <table> {
 }
 widgetPools = <table> {
 }
 BackModelScene = ModelScene {
 }
 FrontModelScene = ModelScene {
 }
 verticalRelativePoint = "BOTTOM"
 horizontalAnchorXOffset = 2
 horizontalAnchorPoint = "LEFT"
 verticalAnchorPoint = "TOP"
 showAndHideOnWidgetSetRegistration = true
}
(*temporary) = Frame {
 horizontalRelativePoint = "RIGHT"
 horizontalRowContainerPool = <table> {
 }
 widgetPools = <table> {
 }
 BackModelScene = ModelScene {
 }
 FrontModelScene = ModelScene {
 }
 verticalRelativePoint = "BOTTOM"
 horizontalAnchorXOffset = 2
 horizontalAnchorPoint = "LEFT"
 verticalAnchorPoint = "TOP"
 showAndHideOnWidgetSetRegistration = true
}
(*temporary) = nil
(*temporary) = "attempt to index field 'BlizzardSettings' (a nil value)"
Addon = <table> {
 IS_WRATH_CLASSIC = false
 Theme = <table> {
 }
 TotemCreatureType = "Totem"
 AurasFilterMode = <table> {
 }
 ANCHOR_POINT_SETPOINT = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 UIScale = 1
 Font = <table> {
 }
 WOW_USES_CLASSIC_NAMEPLATES = false
 IGNORED_STYLES = <table> {
 }
 PlatesByUnit = <table> {
 }
 Animations = <table> {
 }
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 IS_TBC_CLASSIC = false
 MODE_FOR_STYLE = <table> {
 }
 TotemInformation = <table> {
 }
 ON_UPDATE_PER_FRAME = 0.016667
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 Debug = <table> {
 }
 PlatesByGUID = <table> {
 }
 EventHandler = <table> {
 }
 LibUTF8 = <table> {
 }
 Logging = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 ANCHOR_POINT = <table> {
 }
 PlayerName = "Karpana"
 TOTEMS = <table> {
 }
 SCRIPT_FUNCTIONS = <table> {
 }
 ON_UPDATE_INTERVAL = 0.250000
 IS_CATA_CLASSIC = false
 IS_CLASSIC = false
 LibAceConfigRegistry = <table> {
 }
 LibAceConfigDialog = <table> {
 }
 db = <table> {
 }
 WIDGET_EVENTS = <table> {
 }
 IS_CLASSIC_SOD = false
 Widgets = <table> {
 }
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 IS_TWW = false
 Cache = <table> {
 }
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 IS_MAINLINE = true
 LibCustomGlow = <table> {
 }
 DEFAULT_FONT = "Cabin"
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 BackdropTemplate = "BackdropTemplate"
 DEBUG = true
 LibSharedMedia = <table> {
 }
 PlatesCreated = <table> {
 }
 Data = <table> {
 }
 LEGACY_CUSTOM_NAMEPLATES = <table> {
 }
 DEFAULT_SMALL_FONT = "Arial Narrow"
 PlayerClass = "PALADIN"
 GLOW_TYPES = <table> {
 }
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 PlatesVisible = <table> {
 }
}
```






```lua
6289x ...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:337: attempt to index field 'BlizzardSettings' (a nil value)
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:337: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:335>
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1286: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1262>

Locals:
tp_frame = ThreatPlatesFrameNamePlate1 {
 WidgetContainer = Frame {
 }
 stylename = ""
 Parent = NamePlate1 {
 }
 unitcache = <table> {
 }
 widgets = <table> {
 }
 style = <table> {
 }
 IsOccluded = false
 Active = true
 visual = <table> {
 }
 unit = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'BlizzardSettings' (a nil value)"
Addon = <table> {
 IS_WRATH_CLASSIC = false
 Theme = <table> {
 }
 TotemCreatureType = "Totem"
 AurasFilterMode = <table> {
 }
 ANCHOR_POINT_SETPOINT = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 UIScale = 1
 Font = <table> {
 }
 WOW_USES_CLASSIC_NAMEPLATES = false
 IGNORED_STYLES = <table> {
 }
 PlatesByUnit = <table> {
 }
 Animations = <table> {
 }
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 IS_TBC_CLASSIC = false
 MODE_FOR_STYLE = <table> {
 }
 TotemInformation = <table> {
 }
 ON_UPDATE_PER_FRAME = 0.016667
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 Debug = <table> {
 }
 PlatesByGUID = <table> {
 }
 EventHandler = <table> {
 }
 LibUTF8 = <table> {
 }
 Logging = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 ANCHOR_POINT = <table> {
 }
 PlayerName = "Karpana"
 TOTEMS = <table> {
 }
 SCRIPT_FUNCTIONS = <table> {
 }
 ON_UPDATE_INTERVAL = 0.250000
 IS_CATA_CLASSIC = false
 IS_CLASSIC = false
 LibAceConfigRegistry = <table> {
 }
 LibAceConfigDialog = <table> {
 }
 db = <table> {
 }
 WIDGET_EVENTS = <table> {
 }
 IS_CLASSIC_SOD = false
 Widgets = <table> {
 }
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 IS_TWW = false
 Cache = <table> {
 }
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 IS_MAINLINE = true
 LibCustomGlow = <table> {
 }
 DEFAULT_FONT = "Cabin"
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 BackdropTemplate = "BackdropTemplate"
 DEBUG = true
 LibSharedMedia = <table> {
 }
 PlatesCreated = <table> {
 }
 Data = <table> {
 }
 LEGACY_CUSTOM_NAMEPLATES = <table> {
 }
 DEFAULT_SMALL_FONT = "Arial Narrow"
 PlayerClass = "PALADIN"
 GLOW_TYPES = <table> {
 }
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 PlatesVisible = <table> {
 }
}
```




```lua
38x ...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1869: attempt to call field 'UnitBuff' (a nil value)
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1869: in function `UNIT_AURA'
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1965: in main chunk

Locals:
event = nil
unitid = nil
(for index) = 1
(for limit) = 40
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = "player"
(*temporary) = 1
(*temporary) = "PLAYER"
(*temporary) = "attempt to call field 'UnitBuff' (a nil value)"
_G = <table> {
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 HealBot_Options_LoadSpellsbText = HealBot_Options_LoadSpellsbText {
 }
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 784
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 ClassTrialTimerDisplayMixin = <table> {
 }
 DetailsBarra_4_6BorderRight = DetailsBarra_4_6BorderRight {
 }
 GP_ScannerTooltipTexture26 = GP_ScannerTooltipTexture26 {
 }
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 MerchantItem7AltCurrencyFrameItem1Text = MerchantItem7AltCurrencyFrameItem1Text {
 }
 OPTION_SHOW_ACTION_BAR5_TOOLTIP = "Attached to the left side of Action Bar 4 by default"
 BINDING_NAME_NAMEPLATES = "Show Enemy Nameplates"
 CHAT_HEADER_SUFFIX = ": "
 HealBot_Options_AutoShowButtonNormalTexture = HealBot_Options_AutoShowButtonNormalTexture {
 }
 COVENANT_MISSIONS_HEALTH = "Health"
 HealBot_Debug_FrameText31 = HealBot_Debug_FrameText31 {
 }
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 DUNGEON_FLOOR_UPPERBLACKROCKSPIRE3 = "Hall of Blackhand"
 BW_VirtualTooltipTexture30 = BW_VirtualTooltipTexture30 {
 }
 ChatFrame6EditBoxFocusMid = ChatFrame6EditBoxFocusMid {
 }
 AceConfigDialogTooltipTexture20 = AceConfigDialogTooltipTexture20 {
 }
 HealBot_Options_BackupBuffWellFedItemsButton = HealBot_Options_BackupBuffWellFedItemsButton {
 }
 LE_GAME_ERR_ONLY_ONE_QUIVER = 36
 INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 IAT_Achievement_9_114 = IAT_Achievement_9_114 {
 }
 AllTheThings-Settings-Interface-Ad-Hoc Window Updates = AllTheThings-Settings-Interface-Ad-Hoc Window Updates {
 }
 Boss1TargetFrameValue = Boss1TargetFrameValue {
 }
 HEALBOT_OPTIONS_ALSO_WHEN_MOUNTED = "also when mounted"
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 HealBot_Options_Bind4Icon = HealBot_Options_Bind4Icon {
 }
 LE_GAME_ERR_AZERITE_ESSENCE_SELECTION_FAILED_ESSENCE_NOT_UNLOCKED = 1075
 DUNGEON_FLOOR_DRAGONBLIGHTCHROMIESCENARIO2 = "Andorhal"
 L = <table> {
 }
 HealBot_Options_OverridePlayerTargetFramesText = HealBot_Options_OverridePlayerTargetFramesText {
 }
 WL_DESC_LOCATION = "Show/hide your location in a movable tooltip."
 WowTokenRedemptionFrameBg = WowTokenRedemptionFrameBg {
 }
 HEALBOT_ELIXIR_OF_POISON_RES = 3386
 LAG_TOLERANCE = "Lag Tolerance"
 oilvlrelictooltip1Texture26 = oilvlrelictooltip1Texture26 {
 }
 STABLE_PET_ABILITIES_LIST_HEADER = "Special Abilities"
 SendStationeryBackgroundRight = SendStationeryBackgroundRight {
 }
 HekiliDB = <table> {
 }
 TUTORIAL61_SPELLID_DRUID = "768"
 CONQUEST_BAR = "Conquest %d / %d"
 MultiBarLeftButton9Border = MultiBarLeftButton9Border {
 }
 LE_GAME_ERR_NOT_ON_TOURNAMENT_REALM = 889
 UIWidgetCenterDisplayFrameText = UIWidgetCenterDisplayFrameText {
 }
 h = OIlvlCopyEB_bodyBackground {
 }
 OPTION_TOOLTIP_SHOW_ACCOUNT_ACHIEVEMENTS = "Turning this option on will only display your character achievements when people inspect you or use the Blizzard website or mobile app."
 SPIRIT_HEALER_RELEASE_RED = "|cffff2020Spirit Healer|r"
 OPTION_TOOLTIP_FIX_LAG = "Enabling this reduces user interface lag, but may drastically reduce frame rates."
 ARTIFACT_XP_FULL = "%s is at max level."
 VOICEMACRO_8_Tr_1_FEMALE = "Cure me!"
 UnitPopupCommunitiesKickFriendButtonMixin = <table> {
 }
 CompactArenaFrameMember4HealthBarBackground = CompactArenaFrameMember4HealthBarBackground {
 }
 NEWBIE_TOOLTIP_ACHIEVEMENT = "View information about your achievements and statistics."
 LE_FRAME_TUTORIAL_TRANSMOG_MODEL_CLICK = 36
 HealBot_Options_TooltipPosButtonPushedTexture = HealBot_Options_TooltipPosButtonPushedTexture {
 }
 VOICEMACRO_8_Tr_1 = "Heal me!"
 CompactRaidFrameManagerDisplayFrameEveryoneIsAssistButton = CompactRaidFrameManagerDisplayFrameEvery
 ```

**Comment by Backupiseasy** [comment]
This issue should be fixed now with the newest update 11.0.4.

**Comment by karpana** [comment]
> This issue should be fixed now with the newest update 11.0.4.
Thank you.   BugSack is no longer screaming at me.

But I think one of the errors is still left... and is preventing the threat plates from presenting.

```lua
150x ...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1869: attempt to call field 'UnitBuff' (a nil value)
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1869: in function `UNIT_AURA'
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1965: in main chunk

Locals:
event = nil
unitid = nil
(for index) = 1
(for limit) = 40
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = "player"
(*temporary) = 1
(*temporary) = "PLAYER"
(*temporary) = "attempt to call field 'UnitBuff' (a nil value)"
_G = <table> {
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 HealBot_Options_LoadSpellsbText = HealBot_Options_LoadSpellsbText {
 }
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 784
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 ClassTrialTimerDisplayMixin = <table> {
 }
 DetailsBarra_4_6BorderRight = DetailsBarra_4_6BorderRight {
 }
 GP_ScannerTooltipTexture26 = GP_ScannerTooltipTexture26 {
 }
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 MerchantItem7AltCurrencyFrameItem1Text = MerchantItem7AltCurrencyFrameItem1Text {
 }
 OPTION_SHOW_ACTION_BAR5_TOOLTIP = "Attached to the left side of Action Bar 4 by default"
 BINDING_NAME_NAMEPLATES = "Show Enemy Nameplates"
 CHAT_HEADER_SUFFIX = ": "
 HealBot_Options_AutoShowButtonNormalTexture = HealBot_Options_AutoShowButtonNormalTexture {
 }
 COVENANT_MISSIONS_HEALTH = "Health"
 HealBot_Debug_FrameText31 = HealBot_Debug_FrameText31 {
 }
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 DUNGEON_FLOOR_UPPERBLACKROCKSPIRE3 = "Hall of Blackhand"
 BW_VirtualTooltipTexture30 = BW_VirtualTooltipTexture30 {
 }
 ChatFrame6EditBoxFocusMid = ChatFrame6EditBoxFocusMid {
 }
 AceConfigDialogTooltipTexture20 = AceConfigDialogTooltipTexture20 {
 }
 HealBot_Options_BackupBuffWellFedItemsButton = HealBot_Options_BackupBuffWellFedItemsButton {
 }
 LE_GAME_ERR_ONLY_ONE_QUIVER = 36
 INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 IAT_Achievement_9_114 = IAT_Achievement_9_114 {
 }
 AllTheThings-Settings-Interface-Ad-Hoc Window Updates = AllTheThings-Settings-Interface-Ad-Hoc Window Updates {
 }
 Boss1TargetFrameValue = Boss1TargetFrameValue {
 }
 HEALBOT_OPTIONS_ALSO_WHEN_MOUNTED = "also when mounted"
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 HealBot_Options_Bind4Icon = HealBot_Options_Bind4Icon {
 }
 LE_GAME_ERR_AZERITE_ESSENCE_SELECTION_FAILED_ESSENCE_NOT_UNLOCKED = 1075
 DUNGEON_FLOOR_DRAGONBLIGHTCHROMIESCENARIO2 = "Andorhal"
 L = <table> {
 }
 HealBot_Options_OverridePlayerTargetFramesText = HealBot_Options_OverridePlayerTargetFramesText {
 }
 WL_DESC_LOCATION = "Show/hide your location in a movable tooltip."
 WowTokenRedemptionFrameBg = WowTokenRedemptionFrameBg {
 }
 HEALBOT_ELIXIR_OF_POISON_RES = 3386
 LAG_TOLERANCE = "Lag Tolerance"
 oilvlrelictooltip1Texture26 = oilvlrelictooltip1Texture26 {
 }
 STABLE_PET_ABILITIES_LIST_HEADER = "Special Abilities"
 SendStationeryBackgroundRight = SendStationeryBackgroundRight {
 }
 HekiliDB = <table> {
 }
 TUTORIAL61_SPELLID_DRUID = "768"
 CONQUEST_BAR = "Conquest %d / %d"
 MultiBarLeftButton9Border = MultiBarLeftButton9Border {
 }
 LE_GAME_ERR_NOT_ON_TOURNAMENT_REALM = 889
 UIWidgetCenterDisplayFrameText = UIWidgetCenterDisplayFrameText {
 }
 h = OIlvlCopyEB_bodyBackground {
 }
 OPTION_TOOLTIP_SHOW_ACCOUNT_ACHIEVEMENTS = "Turning this option on will only display your character achievements when people inspect you or use the Blizzard website or mobile app."
 SPIRIT_HEALER_RELEASE_RED = "|cffff2020Spirit Healer|r"
 OPTION_TOOLTIP_FIX_LAG = "Enabling this reduces user interface lag, but may drastically reduce frame rates."
 ARTIFACT_XP_FULL = "%s is at max level."
 VOICEMACRO_8_Tr_1_FEMALE = "Cure me!"
 UnitPopupCommunitiesKickFriendButtonMixin = <table> {
 }
 CompactArenaFrameMember4HealthBarBackground = CompactArenaFrameMember4HealthBarBackground {
 }
 NEWBIE_TOOLTIP_ACHIEVEMENT = "View information about your achievements and statistics."
 LE_FRAME_TUTORIAL_TRANSMOG_MODEL_CLICK = 36
 HealBot_Options_TooltipPosButtonPushedTexture = HealBot_Options_TooltipPosButtonPushedTexture {
 }
 VOICEMACRO_8_Tr_1 = "Heal me!"
 CompactRaidFrameManagerDisplayFrameEveryoneIsAssistButton = CompactRaidFrameManagerDisplayFrameEvery
 ```

**Comment by MetalHeadSeven** [comment]
I'm getting the same new errors after latest update.

**Comment by Backupiseasy** [comment]
Ok, I found out that some code from WoW Classic was also used on retail, but only on Paladins. I upload a fixed version 12.0.5.

**Comment by karpana** [comment]
Agreed...Thankyou for the quick fix.
